# Generated by Django 5.0.1 on 2024-04-15 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("upload", models.FileField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("restaurant_name", models.CharField(max_length=100)),
                ("restaurant_address", models.CharField(max_length=200)),
                ("restaurant_city", models.CharField(max_length=100)),
                ("restaurant_state", models.CharField(max_length=100)),
                ("restaurant_zip", models.CharField(max_length=100)),
                ("consumption_date_time", models.DateTimeField()),
                ("symptoms", models.TextField()),
                ("symptoms_start_date_time", models.DateTimeField()),
                ("symptoms_stopped", models.BooleanField(default=False)),
                ("suspected_illness_source", models.TextField()),
                ("additional_info", models.TextField()),
                ("file_name", models.CharField(blank=True, max_length=200, null=True)),
                ("admin_comment", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("In Progress", "In Progress"),
                            ("Resolved", "Resolved"),
                        ],
                        default="New",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
