# Generated by Django 5.0.1 on 2024-04-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Evidence",
        ),
        migrations.RemoveField(
            model_name="report",
            name="file_name",
        ),
        migrations.AddField(
            model_name="report",
            name="file_names",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
